config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :stimulus_tutorials
  get 'messages/new'
  get 'messages/create'
  resources :rooms do
    resources :messages
  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  get '/home', to: 'home#index'
  get '/turbostreams', to: 'home#turbostreams'


authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/stimulus_tutorial.rb
class StimulusTutorial < ApplicationRecord
end

app/controllers/stimulus_tutorials_controller.rb
class StimulusTutorialsController < ApplicationController
  before_action :set_stimulus_tutorial, only: %i[ show edit update destroy ]

  # GET /stimulus_tutorials or /stimulus_tutorials.json
  def index
    @stimulus_tutorials = StimulusTutorial.all
  end

  # GET /stimulus_tutorials/1 or /stimulus_tutorials/1.json
  def show
  end

  # GET /stimulus_tutorials/new
  def new
    @stimulus_tutorial = StimulusTutorial.new
  end

  # GET /stimulus_tutorials/1/edit
  def edit
  end

  # POST /stimulus_tutorials or /stimulus_tutorials.json
  def create
    @stimulus_tutorial = StimulusTutorial.new(stimulus_tutorial_params)

    respond_to do |format|
      if @stimulus_tutorial.save
        format.html { redirect_to stimulus_tutorial_url(@stimulus_tutorial), notice: "Stimulus tutorial was successfully created." }
        format.json { render :show, status: :created, location: @stimulus_tutorial }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stimulus_tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stimulus_tutorials/1 or /stimulus_tutorials/1.json
  def update
    respond_to do |format|
      if @stimulus_tutorial.update(stimulus_tutorial_params)
        format.html { redirect_to stimulus_tutorial_url(@stimulus_tutorial), notice: "Stimulus tutorial was successfully updated." }
        format.json { render :show, status: :ok, location: @stimulus_tutorial }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stimulus_tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stimulus_tutorials/1 or /stimulus_tutorials/1.json
  def destroy
    @stimulus_tutorial.destroy!

    respond_to do |format|
      format.html { redirect_to stimulus_tutorials_url, notice: "Stimulus tutorial was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stimulus_tutorial
      @stimulus_tutorial = StimulusTutorial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stimulus_tutorial_params
      params.fetch(:stimulus_tutorial, {})
    end
end

app/helpers/stimulus_tutorials_helper.rb
module StimulusTutorialsHelper
end

app/views/stimulus_tutorials/_form.html.erb
<%= form_with(model: stimulus_tutorial) do |form| %>
  <% if stimulus_tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stimulus_tutorial.errors.count, "error") %> prohibited this stimulus_tutorial from being saved:</h2>

      <ul>
      <% stimulus_tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <% if stimulus_tutorial.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', stimulus_tutorial, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if stimulus_tutorial.persisted? %>
      <%= link_to "Cancel", stimulus_tutorial, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", stimulus_tutorials_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/stimulus_tutorials/_stimulus_tutorial.html.erb
<div id="<%= dom_id stimulus_tutorial %>">
</div>

app/views/stimulus_tutorials/edit.html.erb
<h1>Edit Stimulus_tutorial</h1>

<%= render 'form', stimulus_tutorial: @stimulus_tutorial %>

app/views/stimulus_tutorials/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Stimulus Tutorials</h1>
  </div>

  <div class="col-sm-6 text-end">
    <%= link_to new_stimulus_tutorial_path, class: 'btn btn-primary' do %>
      Add New Stimulus tutorial
    <% end %>

  </div>

  <div data-controller="stimulus-tutorial" data-stimulus-tutorial-number-value=4>
    <!--    <h1 data-target="stimulus-tutorial.output"></h1>-->
    <h1 data-stimulus-tutorial-target="output"></h1>

    <button data-action="stimulus-tutorial#clicked"> CLICK ME</button>
  </div>


  <div data-controller="text-input">
    <input type="text" data-action="text-input#changed" data-text-input-target="input">
    <h1 data-text-input-target="output"></h1>
  </div>

  <div data-controller="styling" data-styling-primary-class="btn-primary">
    <button class='btn' data-styling-target="button" data-action="styling#clicked">
      CLICK ME
    </button>
  </div>

  <div data-controller="styling" data-styling-primary-class="btn-primary">
    <button class='btn' data-styling-target="button" data-action="styling#clicked:once">
      CLICK ME
    </button>
  </div>
</div>

app/views/stimulus_tutorials/new.html.erb
<h1>New stimulus_tutorial</h1>

<%= render 'form', stimulus_tutorial: @stimulus_tutorial %>

app/views/stimulus_tutorials/show.html.erb
<div class="page-header">
  <%= link_to stimulus_tutorials_path, class: 'btn btn-default' do %>
    All Stimulus_tutorials
  <% end %>
  <%= link_to edit_stimulus_tutorial_path(@stimulus_tutorial), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show stimulus_tutorial</h1>
</div>

<dl class="dl-horizontal">
</dl>