config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :stimulus_tutorials
  get 'messages/new'
  get 'messages/create'
  resources :rooms do
    resources :messages
  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  get '/home', to: 'home#index'
  get '/turbostreams', to: 'home#turbostreams'


authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def turbostreams
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
  def terms
  end

  def privacy
  end
end

app/views/home/index.html.erb
<h1>Welcome to Jumpstart!</h1>
<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>

<p>Go Rails Tutorial</p>
<%= link_to "Turbostreams example", turbostreams_path %>
<p>-------------------------------------------------------------------</p>
<p>Drifting Ruby Episode #272</p>
<%= link_to "Drifting Ruby Episode #272", stimulus_tutorials_path %>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>

app/views/home/turbostreams.html.erb
<h1>Welcome to Jumpstart!</h1>
<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>

<%= button_to "Do something", turbostreams_path , method: :get, data: {turbo_stream: :true }%>

<div id="example"></div>


<div class="todo"></div>
<div class="todo"></div>
<div class="todo"></div>
<div class="todo"></div>
<div class="todo"></div>
<div class="todo"></div>

app/views/home/turbostreams.turbo_stream.erb
<%= turbo_stream_action_tag "console_log", targets: ".todo", plain: "Hello World", template: "Content"%>
<%= turbo_stream_action_tag "notification", title: "Hello World 2" %>