config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :stimulus_tutorials
  get 'messages/new'
  get 'messages/create'
  resources :rooms do
    resources :messages
  end
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  get '/home', to: 'home#index'
  get '/turbostreams', to: 'home#turbostreams'


authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages

  broadcasts
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if room.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', room, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if room.persisted? %>
      <%= link_to "Cancel", room, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", rooms_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<p id=" dom_id room">
  <strong>Name:</strong>
  <%= room.name %>
</p>

app/views/rooms/edit.html.erb
<h1>Edit Room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render 'form', room: @room %>

  <%= link_to 'Show', @room %>
  <%= link_to 'Back', rooms_path %>
<% end %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Rooms</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Add New Room
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <%= content_tag :tr, id: dom_id(room), class: dom_class(room) do %>
          
            <td><%= link_to room.name, room %></td>
          

          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<%= turbo_stream_from @room %>

<%= turbo_frame_tag "room" do %>
  <%= render @room %>
  <p>
    <%= link_to 'Edit', edit_room_path(@room) %>
    <%= link_to 'Back', rooms_path, "data-turbo-frame": "_top"  %>
  </p>
<% end %>

<div id="messages">
  <%= render @room.messages %>
</div>

<%= link_to "New Message", new_room_message_path(@room) %>
<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>